<?php

/**
 * @file
 * Allows Cross-origin resource sharing.
 */

/**
 * Implements hook_menu().
 */
function cors_menu() {
  $items = array();

  $items['admin/config/services/cors'] = array(
    'title' => 'CORS',
    'description' => 'Enable Cross-origin resource sharing',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cors_admin_form'),
    'access arguments' => array('Administer site configuration'),
  );

  return $items;
}

/**
 * CORS admin configuration form.
 */
function cors_admin_form($form, &$form_state) {
  $form = array();

  $cors_domains = '';
  foreach (variable_get('cors_domains', array()) as $path => $domain) {
    $cors_domains .= $path . '|' . $domain . "\n";
  }

  $form['cors_domains'] = array(
    '#type' => 'textarea',
    '#title' => t('Domains'),
    '#description' => t('A list of paths and corresponding domains to enable for CORS. Enter one value per line separated by a pipe, in this order:
   <ul>
     <li>Internal path</li>
     <li>Access-Control-Allow-Origin</li>
     <li>Access-Control-Allow-Methods</li>
     <li>Access-Control-Allow-Headers</li>
    </ul>
    Examples:
    <ul>
      <li>*|http://example.com</li>
      <li>api|http://example.com:8080 http://example.com</li>
      <li>api/*|https://example.com</li>
      <li>api/*|*|POST|Content-Type</li>
    </ul>'),
    '#default_value' => $cors_domains,
    '#rows' => 10,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save configuration'),
  );

  return $form;
}

/**
 * CORS admin configuration form submit.
 */
function cors_admin_form_submit($form, &$form_state) {
  $domains = explode("\n", $form_state['values']['cors_domains'], 2);
  $settings = array();
  foreach ($domains as $domain) {
    $domain = explode("|", $domain, 2);
    if (count($domain) === 2) {
      $settings[$domain[0]] = (isset($settings[$domain[0]])) ? $settings[$domain[0]] . ' ' : '';
      $settings[$domain[0]] .= trim($domain[1]);
    }
  }

  variable_set('cors_domains', $settings);
}

/**
 * Implements hook_init().
 */
function cors_init() {
  $domains = variable_get('cors_domains', array());
  $current_path = drupal_strtolower(drupal_get_path_alias($_GET['q']));
  $headers = array(
    'all' => array(
      'Access-Control-Allow-Origin' => array(),
    ),
    'OPTIONS' => array(
      'Access-Control-Allow-Methods' => array(),
      'Access-Control-Allow-Headers' => array(),
    ),
  );
  foreach ($domains as $path => $settings) {
    $settings = explode("|", $settings);
    $page_match = drupal_match_path($current_path, $path);
    if ($current_path != $_GET['q']) {
      $page_match = $page_match || drupal_match_path($_GET['q'], $path);
    }
    if ($page_match) {
      if (!empty($settings[0])) {
        $headers['all']['Access-Control-Allow-Origin'][] = trim($settings[0]);
      }
      if (!empty($settings[1])) {
        $headers['OPTIONS']['Access-Control-Allow-Methods'][] = trim($settings[1]);
      }
      if (!empty($settings[2])) {
        $headers['OPTIONS']['Access-Control-Allow-Headers'][] = trim($settings[2]);
      }
    }
  }

  foreach ($headers as $method => $allowed) {
    if ($method === 'all' || $method === $_SERVER['REQUEST_METHOD']) {
      foreach ($allowed as $header => $values) {
        if (!empty($values)) {
          drupal_add_http_header($header, implode(' ', $values), TRUE);
        }
      }
    }
  }
}

